/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import model.confidential.Authentication;
import model.confidential.Credentials;
import model.confidential.Fileload;
import model.hospital.CommunnityCatalog;
import model.hospital.Hospitaldirectory;
import model.patienta.Encounter;
import model.patienta.Patient;
import model.patienta.Patientdirectory;
import model.persona.Community;
import model.persona.Persondirectory;
import userinterface.Homepagemjf;
import userinterface.communitya.CreateCommunity;
import userinterface.patient.PatAppView;
import userinterface.patient.Patientloginview;
import userinterface.patient.Patientloginview;

/**
 *
 * @author amey8
 */
public class Patientjf extends javax.swing.JFrame {

    /**
     * Creates new form Patientjf
     */
    Patientdirectory patdir;
    Patient patient ;
    Community community;
    Authentication auth;
    Hospitaldirectory hosdir;
    Encounter enc;
    Persondirectory perdir;
    Credentials cred1;
    CommunnityCatalog c;
    int curr_patient_id;
    public Patientjf() {
        initComponents();
        this.c=new CommunnityCatalog();
    }
    public void initpatientdir(Patientdirectory patdir,int patient_id)
    {
            this.patdir=patdir; 
            curr_patient_id =patient_id;
    }
    public void initcurrpatient(Patient patient,Community community,Patientdirectory patdir,
            Authentication auth,Hospitaldirectory hosdir,Persondirectory perdir)
    {
        this.patient  = patient;   
        this.community=community;
        this.patdir=patdir;
        this.auth=auth;
        this.hosdir=hosdir;
        this.enc= new Encounter();
        this.perdir=perdir;
        jlusername.setText(patient.getUsername());
        cred1 = new Credentials(patient.getUsername(),"Patient","xyz",1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        PLeftMenu = new javax.swing.JPanel();
        jLabell = new javax.swing.JLabel();
        jlusername = new javax.swing.JLabel();
        javax.swing.JButton btnprofile = new javax.swing.JButton();
        javax.swing.JButton btnappointment = new javax.swing.JButton();
        javax.swing.JButton btnSignout = new javax.swing.JButton();
        javax.swing.JButton btnappointment1 = new javax.swing.JButton();
        PRightContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AAROGYA MED NETWORK");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jSplitPane1.setBackground(new java.awt.Color(204, 204, 255));

        PLeftMenu.setOpaque(false);

        jLabell.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabell.setText("Logged in as");
        jLabell.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlusername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlusername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnprofile.setBackground(new java.awt.Color(204, 204, 204));
        btnprofile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnprofile.setText("View Profile");
        btnprofile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnprofile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofileActionPerformed(evt);
            }
        });

        btnappointment.setBackground(new java.awt.Color(204, 204, 204));
        btnappointment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnappointment.setText("Appointments");
        btnappointment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnappointment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnappointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnappointmentActionPerformed(evt);
            }
        });

        btnSignout.setBackground(new java.awt.Color(204, 204, 204));
        btnSignout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignout.setText("Sign Out");
        btnSignout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoutActionPerformed(evt);
            }
        });

        btnappointment1.setBackground(new java.awt.Color(204, 204, 204));
        btnappointment1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnappointment1.setText("Community");
        btnappointment1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnappointment1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnappointment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnappointment1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PLeftMenuLayout = new javax.swing.GroupLayout(PLeftMenu);
        PLeftMenu.setLayout(PLeftMenuLayout);
        PLeftMenuLayout.setHorizontalGroup(
            PLeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PLeftMenuLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(PLeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PLeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PLeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSignout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnappointment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addComponent(btnprofile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnappointment1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PLeftMenuLayout.setVerticalGroup(
            PLeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLeftMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlusername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnappointment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnappointment1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(PLeftMenu);

        javax.swing.GroupLayout PRightContentLayout = new javax.swing.GroupLayout(PRightContent);
        PRightContent.setLayout(PRightContentLayout);
        PRightContentLayout.setHorizontalGroup(
            PRightContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        PRightContentLayout.setVerticalGroup(
            PRightContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(PRightContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoutActionPerformed
        // TODO add your handling code here:
        Fileload fileload = new Fileload();
        fileload.loadpatientfile( patdir);
        fileload.loadaddressfile(community);
        fileload.loadcredentialsfile(auth);
        fileload.loadhospitalfile(hosdir);
        fileload.loadencounterfile(enc);
        fileload.loadpersonfile(perdir);
        Homepagemjf home=new Homepagemjf();
        home.setVisible(rootPaneCheckingEnabled);
        dispose();
    }//GEN-LAST:event_btnSignoutActionPerformed

    private void btnappointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnappointmentActionPerformed
        // TODO add your handling code here:
         PatAppView pav = new PatAppView(enc,patient.getPatient_id());
        jSplitPane1.setRightComponent(pav);
        
    }//GEN-LAST:event_btnappointmentActionPerformed

    private void btnprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofileActionPerformed
        // TODO add your handling code here:
            Patientloginview profile = new Patientloginview(patient,community,patdir, auth,perdir);
         jSplitPane1.setRightComponent(profile);
    }//GEN-LAST:event_btnprofileActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Fileload fileload = new Fileload();
        fileload.loadpatientfile( patdir);
        fileload.loadaddressfile(community);
        fileload.loadcredentialsfile(auth);
        fileload.loadhospitalfile(hosdir);
        fileload.loadencounterfile(enc);
        fileload.loadpersonfile(perdir);
        
    }//GEN-LAST:event_formWindowClosing

    private void btnappointment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnappointment1ActionPerformed
        // TODO add your handling code here:
        CreateCommunity pa=new CreateCommunity(c,cred1);
         jSplitPane1.setRightComponent(pa);
    }//GEN-LAST:event_btnappointment1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patientjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patientjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patientjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patientjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patientjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PLeftMenu;
    private javax.swing.JPanel PRightContent;
    private javax.swing.JLabel jLabell;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel jlusername;
    // End of variables declaration//GEN-END:variables
}
