/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.confidential.Authentication;
import model.confidential.Credentials;
import model.confidential.Fileload;
import model.confidential.Validations;
import model.hospital.Hospital;
import model.hospital.Hospitaldirectory;
import model.patienta.Patient;
import model.patienta.Patientdirectory;
import model.persona.Address;
import model.persona.Community;
import model.persona.Persondirectory;
/**
 *
 * @author amey8
 */

public class PatientActions extends javax.swing.JPanel {

    /**
     * Creates new form PatientCrud
     */
        Credentials cred;
    Authentication auth;
    Community community;
    Patientdirectory patdir;
    Hospitaldirectory hosdir;
    Persondirectory perdir;
    Patient pat;
    public PatientActions(Community community,Patientdirectory patdir,Authentication auth,Credentials cred,
            Hospitaldirectory hosdir,Persondirectory perdir,Patient pat) {
        initComponents();
        this.community=community;
        this.patdir=patdir;
        this.auth=auth;
        this.cred=cred;
        this.hosdir=hosdir;
        this.perdir=perdir;
        this.pat=pat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tffirstname = new javax.swing.JTextField();
        tflastname = new javax.swing.JTextField();
        tfage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listgender = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfmobileno = new javax.swing.JTextField();
        tfemailid = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfstreet = new javax.swing.JTextField();
        tfunit = new javax.swing.JTextField();
        tfcity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfstate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfzipcode = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        tfpassword = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnsregister = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 450));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Personal Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("First Name");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Last Name");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Age");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gender");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tffirstname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tflastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflastnameActionPerformed(evt);
            }
        });

        tfage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfageActionPerformed(evt);
            }
        });

        listgender.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Male", "Female", "Other", "Don't need to reveal" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listgender.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(listgender);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tflastname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfage, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tflastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Contact Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mobile Number");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email id");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfemailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfemailid, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(tfemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(tfmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Address", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Street");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Unit");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("City");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("State");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfstateActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Zipcode");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfzipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfzipcodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfunit, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfstreet, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfcity, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfstate, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Credentials", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Username");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Password");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel14)
                .addComponent(tfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnedit.setBackground(new java.awt.Color(204, 204, 204));
        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnedit.setText("Edit");
        btnedit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnsregister.setBackground(new java.awt.Color(204, 204, 204));
        btnsregister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsregister.setText("Register");
        btnsregister.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsregister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsregisterActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(204, 204, 204));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnupdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(204, 204, 204));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnclear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnsearch.setBackground(new java.awt.Color(204, 204, 204));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(btnsregister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsregister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tflastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflastnameActionPerformed

    private void tfageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfageActionPerformed

    private void tfemailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailidActionPerformed

    private void tfstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfstateActionPerformed

    private void tfzipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfzipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfzipcodeActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:

        btnedit.setEnabled(false);
        btnupdate.setEnabled(true);

        btnsregister.setEnabled(false);
    }//GEN-LAST:event_btneditActionPerformed

    private void btnsregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsregisterActionPerformed
        // TODO add your handling code here:
        btnedit.setEnabled(true);
        btnclear.setEnabled(true);
        //disableViewfield();
        //Patient updpat= new Patient();

        String tfname = tffirstname.getText();
        String tlname = tflastname.getText();
        String tage = tfage.getText();
        String tgender = listgender.getSelectedValue();
        String tmobileno = tfmobileno.getText();
        String temailid = tfemailid.getText();
        String tunit = tfunit.getText();
        String tcity = tfcity.getText();
        String tstreet = tfstreet.getText();
        String tzipcode = tfzipcode.getText();
        String tstate = tfstate.getText();
        String tusername = tfusername.getText();
        String tpassword = tfpassword.getText();

        boolean er = false;

        Validations val = new Validations();
        try {

            if (tfname.isEmpty() || tlname.isEmpty() || tage.isEmpty() || tmobileno.isEmpty() || tgender.isEmpty()
                || listgender.getSelectedValue().isEmpty() || temailid.isEmpty() || tunit.isEmpty()
                || tcity.isEmpty() || tstreet.isEmpty() || tzipcode.isEmpty() || tstate.isEmpty()
                || tusername.isEmpty() || tpassword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cannot enter empty field",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
            } else {
                //Employee emp = new Employee();
                Patient pat1 = new Patient();
                Address add = new Address();

                pat1.setPersonid(9999);
                pat1.setPatient_id(9999);
                add.setAddress_id(9999);

                if (val.valstring(tfname) == false || val.valstring(tlname) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Name in Proper format",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setFirstname(tfname);
                    pat1.setLastname(tlname);

                }
                if (!val.valage(tage) || Integer.valueOf(tage) <= 0 || Integer.valueOf(tage) > 200) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Age",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setAge(Integer.valueOf(tage));
                    pat1.setGender(tgender);
                }
                if (!val.valnumber(tmobileno)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Mobile Number",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setMobileno(tmobileno);

                }

                if (val.valemailid(temailid) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Email id",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setEmail(temailid);
                }
                if (val.valstring(tcity) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter City Name in Proper format",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {

                    add.setCity(tcity);
                    add.setUnit(tunit);
                    add.setStreet(tstreet);
                }

                if (val.valstring(tstate) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Name in Proper format",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    add.setState(tstate);
                }
                if (!val.valnum(tzipcode)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Zipcode",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    add.setZipcode(tzipcode);
                    // pat.setMobileno(Integer.valueOf(tzipcode));
                }
                if (val.valpassword(tpassword, patdir.getPatientcatalog()) == false) {
                    JOptionPane.showMessageDialog(this, "Please Password in Proper format (a-z,A-Z,_,$,@)",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setPassword(tpassword);
                }
                if (val.valusername(tusername, patdir.getPatientcatalog()) == 1) {

                    JOptionPane.showMessageDialog(this, "Please username in Proper format (a-z,A-Z,_)",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                }else if (val.valusername(tusername, patdir.getPatientcatalog()) == 2) {

                    JOptionPane.showMessageDialog(this, "Please choose different username",
                        "UserName already exists,Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setUsername(tusername);

                }
                if (er != true) {

                    //catalog.addnewemployee(emp);
                    pat1.setPersonid();

                    pat1.setPatient_id();

                    add.setAddress_id();

                    pat1.setAddressid(add.getAddress_id());

                    patdir.addnewpatient(pat1);

                    perdir.addnewperson(perdir.searchIndexPer(pat.getPersonid()));

                    community.addnewaddress(add);
                    
                    community.addnewaddress(add);
                    Credentials cred= new Credentials(tusername, "Patient", tpassword, pat.getPersonid()-1);
                    auth.addnewcredentials(cred);
                    Fileload file1=new Fileload();
                    file1.loadcredentialsfile(auth);

                    JOptionPane.showMessageDialog(this, "Successfully Patient Profile Created!!!");

                    tffirstname.setText("");
                    tflastname.setText("");
                    tfage.setText("");
                    tfmobileno.setText("");
                    tfstreet.setText("");
                    tfemailid.setText("");
                    tfunit.setText("");
                    tfcity.setText("");
                    listgender.clearSelection();
                    tfstate.setText("");
                    tfzipcode.setText("");
                    tfusername.setText("");
                    tfpassword.setText("");
                }
                else {

                    //catalog.deleteemprec(0);
                    patdir.deletepatientrec(9999);
                    community.deleteaddressrec(9999);
                }}}
                catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Values",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_btnsregisterActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        btnedit.setEnabled(true);
        //disableViewfield();
        //Patient updpat= new Patient();
        btnedit.setEnabled(true);
        btnclear.setEnabled(true);
        //disableViewfield();
        //Patient updpat= new Patient();

        String tfname = tffirstname.getText();
        String tlname = tflastname.getText();
        String tage = tfage.getText();
        String tgender = listgender.getSelectedValue();
        String tmobileno = tfmobileno.getText();
        String temailid = tfemailid.getText();
        String tunit = tfunit.getText();
        String tcity = tfcity.getText();
        String tstreet = tfstreet.getText();
        String tzipcode = tfzipcode.getText();
        String tstate = tfstate.getText();
        String tusername = tfusername.getText();
        String tpassword = tfpassword.getText();

        boolean er = false;

        Validations val = new Validations();
        try {

            if (tfname.isEmpty() || tlname.isEmpty() || tage.isEmpty() || tmobileno.isEmpty() || tgender.isEmpty()
                || listgender.getSelectedValue().isEmpty() || temailid.isEmpty() || tunit.isEmpty()
                || tcity.isEmpty() || tstreet.isEmpty() || tzipcode.isEmpty() || tstate.isEmpty()
                || tusername.isEmpty() || tpassword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cannot enter empty field",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
            } else {
                //Employee emp = new Employee();
                Patient pat1 = new Patient();
                Address add = new Address();

                pat1.setPersonid(9999);
                pat1.setPatient_id(9999);
                add.setAddress_id(9999);

                if (val.valstring(tfname) == false || val.valstring(tlname) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Name in Proper format",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setFirstname(tfname);
                    pat1.setLastname(tlname);

                }
                if (!val.valage(tage) || Integer.valueOf(tage) <= 0 || Integer.valueOf(tage) > 200) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Age",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setAge(Integer.valueOf(tage));
                    pat1.setGender(tgender);
                }
                if (!val.valnumber(tmobileno)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Mobile Number",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setMobileno(tmobileno);
                }

                if (val.valemailid(temailid) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Email id",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setEmail(temailid);
                }
                if (val.valstring(tcity) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter City Name in Proper format",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {

                    add.setCity(tcity);
                    add.setUnit(tunit);
                    add.setStreet(tstreet);
                }

                if (val.valstring(tstate) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Name in Proper format",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    add.setState(tstate);
                }
                if (!val.valnum(tzipcode)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Zipcode",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    add.setZipcode(tzipcode);
                    // pat.setMobileno(Integer.valueOf(tzipcode));
                }
                if (val.valpassword(tpassword, patdir.getPatientcatalog()) == false) {
                    JOptionPane.showMessageDialog(this, "Please Password in Proper format (a-z,A-Z,_,$,@)",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setPassword(tpassword);
                }
                if (val.valusername(tusername, patdir.getPatientcatalog()) == 1) {

                    JOptionPane.showMessageDialog(this, "Please username in Proper format (a-z,A-Z,_)",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    pat1.setUsername(tusername);
                }
                if (er != true) {

                    //catalog.addnewemployee(emp);
                    pat1.setPersonid(pat.getPersonid());
                    pat1.setPatient_id(pat.getPatient_id());
                    add.setAddress_id(pat.getAddressid());
                    
                    pat1.setAddressid(pat.getAddressid());
                    patdir.updatepatient(pat1, pat.getPatient_id());
                    perdir.updatepersonpat(pat1,pat.getPersonid());
                    community.updateaddress(add, pat.getAddressid());
                    

                    JOptionPane.showMessageDialog(this, "Successfully Patient Profile Updated!!!");

                    tffirstname.setText("");
                    tflastname.setText("");
                    tfage.setText("");
                    tfmobileno.setText("");
                    tfstreet.setText("");
                    tfemailid.setText("");
                    tfunit.setText("");
                    tfcity.setText("");
                    listgender.clearSelection();
                    tfstate.setText("");
                    tfzipcode.setText("");
                    tfusername.setText("");
                    tfpassword.setText("");

                }else {

                    //catalog.deleteemprec(0);
                    patdir.deletepatientrec(9999);
                    community.deleteaddressrec(9999);
                }}}
                catch (Exception e) {
                    JOptionPane.showMessageDialog(this,"Please Enter Valid Values",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        //enableViewfield();
        tffirstname.setText("");
        tflastname.setText("");
        tfage.setText("");
        //listgender.setSelectedValue(pat.getGender(), rootPaneCheckingEnabled);
        tfmobileno.setText("");
        tfemailid.setText("");
        tfstreet.setText("");
        tfunit.setText("");
        tfcity.setText("");
        tfstate.setText("");
        tfzipcode.setText("");
        tfusername.setText("");
        tfpassword.setText("");
        //tfdesc.setText("");
        btnedit.setEnabled(true);
        btnupdate.setEnabled(false);
        btnsregister.setEnabled(true);

    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String query;
        Patient hos = new Patient();
        
        if (!tfusername.getText().isEmpty()) {
            query = tfusername.getText();
            for (Patient emp1 : patdir.getPatientcatalog()) {
                if (emp1.getUsername().equalsIgnoreCase(tfusername.getText())) {
                    hos = emp1;
                }
            }
        }else  if (!tffirstname.getText().isEmpty()) {
            query = tffirstname.getText();
            for (Patient emp1 : patdir.getPatientcatalog()) {
                if (emp1.getUsername().equalsIgnoreCase(tffirstname.getText())) {
                    hos = emp1;
                }
            }
        }
         else {
            JOptionPane.showMessageDialog(this,
                    "Search on username or firstname");
        }
        if (hos != null) {
            JOptionPane.showMessageDialog(this,
                    "Patient Found!!!");
            intializefields(community,hos);
            btnsregister.setEnabled(false);
            btnupdate.setEnabled(false);
        } else
            JOptionPane.showMessageDialog(this,
                    "Patient does not exist!!!");
    }//GEN-LAST:event_btnsearchActionPerformed

    public void intializefields(Community community,Patient pat) {
        
        tffirstname.setText(pat.getFirstname());
        tflastname.setText(pat.getLastname());
        tfage.setText(String.valueOf(pat.getAge()));
        
        listgender.setSelectedValue(pat.getGender(), true);
        tfmobileno.setText(pat.getMobileno());
        tfemailid.setText(pat.getEmail());
        Address add = community.searchIndexAddress(pat.getAddressid());
        tfunit.setText(add.getUnit());
        tfcity.setText(add.getCity());
        tfstreet.setText(add.getStreet());
        tfzipcode.setText(add.getZipcode());
        tfstate.setText(add.getZipcode());
        tfusername.setText(pat.getUsername());
        tfpassword.setText(pat.getPassword());
        tfstreet.setText(add.getStreet());
        tfunit.setText(add.getUnit());
        tfcity.setText(add.getCity());
        tfstate.setText(add.getState());
        tfzipcode.setText(add.getZipcode());
        //disableViewfield();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsregister;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listgender;
    private javax.swing.JTextField tfage;
    private javax.swing.JTextField tfcity;
    private javax.swing.JTextField tfemailid;
    private javax.swing.JTextField tffirstname;
    private javax.swing.JTextField tflastname;
    private javax.swing.JTextField tfmobileno;
    private javax.swing.JTextField tfpassword;
    private javax.swing.JTextField tfstate;
    private javax.swing.JTextField tfstreet;
    private javax.swing.JTextField tfunit;
    private javax.swing.JTextField tfusername;
    private javax.swing.JTextField tfzipcode;
    // End of variables declaration//GEN-END:variables
}
