/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.doctora;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.confidential.Authentication;
import model.confidential.Credentials;
import model.hospemp.Doctor;
import model.hospemp.Doctordirectory;
import model.hospital.Hospitaldirectory;
import model.patienta.Patient;
import model.patienta.Patientdirectory;
import model.persona.Address;
import model.persona.Community;
import model.persona.Persondirectory;

/**
 *
 * @author amey8
 */
public class DoctorCatalog extends javax.swing.JPanel {

    /**
     * Creates new form DoctorCatalog
     */
        Credentials cred;
    Authentication auth;
    Community community;
    
    Hospitaldirectory hosdir;
    Persondirectory perdir;
    Doctordirectory docdir;
    Doctor cdr;
    public DoctorCatalog(Community community, Authentication auth, Hospitaldirectory hosdir, 
            Credentials cred, Persondirectory perdir,Doctordirectory docdir) {
        initComponents();
        this.community=community;
        
        this.auth=auth;
        this.cred=cred;
        this.hosdir=hosdir;
        this.perdir=perdir;
        this.docdir=docdir;
        populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpatient = new javax.swing.JTable();
        btndelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tpatient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tpatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Username", "FirstName", "LastName", "Age", "Gender", "MobileNo", "EmailId", "Street", "Unit", "City", "State", "Zipcode", "Spec"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tpatient.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tpatient.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        tpatient.setMinimumSize(new java.awt.Dimension(600, 80));
        tpatient.setPreferredSize(new java.awt.Dimension(600, 80));
        jScrollPane2.setViewportView(tpatient);

        btndelete.setBackground(new java.awt.Color(204, 204, 204));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:

        int row = tpatient.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                "No row is selected! Please select one row",
                "Select row",
                JOptionPane.ERROR_MESSAGE);
            
        } else {
            DefaultTableModel model = (DefaultTableModel) tpatient.getModel();
             String selected_hosid = (String) model.getValueAt(row, 0);
            docdir.deletedoctorrec(selected_hosid);
            //addressdelete
            populatetable();
        }
    }//GEN-LAST:event_btndeleteActionPerformed
      private void populatetable() {
        DefaultTableModel model = (DefaultTableModel) tpatient.getModel();
        model.setRowCount(0);
        Address add;

        for (Doctor pat : docdir.getDocdir()) {
            Object[] row = new Object[14];
            
            row[0] = pat.getUsername();//username
            row[1] = pat.getFirstname();
            row[2] = pat.getLastname();
            row[3] = pat.getAge();
            row[4] = pat.getGender();
            row[5] = pat.getMobileno();
            row[6] = pat.getEmail();

            add = community.searchIndexAddress(pat.getAddressid());
            row[7] = add.getStreet();
            row[8] = add.getUnit();
            row[9] = add.getCity();
            row[10] = add.getState();
            row[11] = add.getZipcode();
            row[12]=pat.getSpec();
            model.addRow(row);
            //JOptionPane.showMessageDialog(this, "Successfully Employee Profile Created!!!");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tpatient;
    // End of variables declaration//GEN-END:variables
}
