/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface.systemadminhome;

import model.confidential.Authentication;
import model.confidential.Credentials;
import model.confidential.Fileload;
import model.hospemp.Doctordirectory;
import model.hospital.CommunnityCatalog;
import model.hospital.Hospitaldirectory;
import model.patienta.Patientdirectory;
import model.persona.Community;
import model.persona.Person;
import model.persona.Persondirectory;
import userinterface.Homepagemjf;
import userinterface.doctora.Doctoractions;
import userinterface.hospitala.Hospitalcatalog;
import userinterface.patient.PatientView;
import userinterface.PatientActions;
import userinterface.communitya.CreateCommunity;
import userinterface.doctora.DoctorCatalog;
/**
 *
 * @author amey8
 */
public class Adminhome extends javax.swing.JFrame {

    /**
     * Creates new form Adminhome
     */
    
    Credentials cred;
    Authentication auth;
    Community community;
    Patientdirectory patdir;
    Hospitaldirectory hosdir;
    Persondirectory perdir;
    Doctordirectory docdir;
    CommunnityCatalog c;
    public Adminhome() {
        initComponents();
        this.c=new CommunnityCatalog();
    }
        
    public void adminhomeinit(Community community,Patientdirectory patdir,Authentication auth,Credentials cred,
            Hospitaldirectory hosdir,Persondirectory perdir)
    {
        this.community=community;
        this.patdir=new Patientdirectory();
        this.auth=auth;
        this.cred=cred;
        this.hosdir=hosdir;
        this.perdir=perdir;
        docdir=new Doctordirectory();
        jlusername.setText(cred.getUsername());
        jlusertype.setText(cred.getUsertype());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabell = new javax.swing.JLabel();
        jlusername = new javax.swing.JLabel();
        javax.swing.JButton btnprofile = new javax.swing.JButton();
        javax.swing.JButton btnSignout = new javax.swing.JButton();
        jlusertype = new javax.swing.JLabel();
        javax.swing.JButton btnpatientcata = new javax.swing.JButton();
        javax.swing.JButton btnhospitalcata = new javax.swing.JButton();
        javax.swing.JButton btnpatientaction = new javax.swing.JButton();
        javax.swing.JButton btndoccata = new javax.swing.JButton();
        javax.swing.JButton btndocaction = new javax.swing.JButton();
        javax.swing.JButton btncommunity = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(950, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AAROGYA MED NETWORK");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jSplitPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setOpaque(false);

        jLabell.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabell.setText("Logged in as");
        jLabell.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlusername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlusername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnprofile.setBackground(new java.awt.Color(204, 204, 204));
        btnprofile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnprofile.setText("View Profile");
        btnprofile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnprofile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofileActionPerformed(evt);
            }
        });

        btnSignout.setBackground(new java.awt.Color(204, 204, 204));
        btnSignout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignout.setText("Sign Out");
        btnSignout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoutActionPerformed(evt);
            }
        });

        jlusertype.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlusertype.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnpatientcata.setBackground(new java.awt.Color(204, 204, 204));
        btnpatientcata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpatientcata.setText("PatientCatalog");
        btnpatientcata.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnpatientcata.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpatientcata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientcataActionPerformed(evt);
            }
        });

        btnhospitalcata.setBackground(new java.awt.Color(204, 204, 204));
        btnhospitalcata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhospitalcata.setText("HospitalCatalog");
        btnhospitalcata.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhospitalcata.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhospitalcata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhospitalcataActionPerformed(evt);
            }
        });

        btnpatientaction.setBackground(new java.awt.Color(204, 204, 204));
        btnpatientaction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpatientaction.setText("PatientActions");
        btnpatientaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnpatientaction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpatientaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientactionActionPerformed(evt);
            }
        });

        btndoccata.setBackground(new java.awt.Color(204, 204, 204));
        btndoccata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndoccata.setText("DoctorCatalog");
        btndoccata.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndoccata.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndoccata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoccataActionPerformed(evt);
            }
        });

        btndocaction.setBackground(new java.awt.Color(204, 204, 204));
        btndocaction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndocaction.setText("DocterActions");
        btndocaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndocaction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndocaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocactionActionPerformed(evt);
            }
        });

        btncommunity.setBackground(new java.awt.Color(204, 204, 204));
        btncommunity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncommunity.setText("Community");
        btncommunity.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncommunity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlusertype, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncommunity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnpatientaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSignout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnpatientcata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnhospitalcata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndocaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndoccata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlusername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlusertype, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpatientcata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpatientaction, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btndoccata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndocaction, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhospitalcata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofileActionPerformed
        // TODO add your handling code here:
        AdminProfile profile = new AdminProfile( perdir,perdir.searchIndexPer(cred.getUsername()), community);
       jSplitPane1.setRightComponent(profile);
    }//GEN-LAST:event_btnprofileActionPerformed

    private void btnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoutActionPerformed
        // TODO add your handling code here:
        Fileload fileload = new Fileload();
        fileload.loadpatientfile( patdir);
        fileload.loadaddressfile(community);
        
        fileload.loadhospitalfile(hosdir);
        fileload.loadpersonfile(perdir);
        fileload.loaddoctorfile(docdir);
        fileload.loadcommunityfile(c);
        Homepagemjf home=new Homepagemjf();
        home.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_btnSignoutActionPerformed

    private void btnpatientcataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientcataActionPerformed
        // TODO add your handling code here:
        PatientView p= new PatientView(community, patdir, auth, cred, hosdir, perdir);
        jSplitPane1.setRightComponent(p);
    }//GEN-LAST:event_btnpatientcataActionPerformed

    private void btnhospitalcataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhospitalcataActionPerformed
        // TODO add your handling code here:
        Hospitalcatalog profile = new Hospitalcatalog(community,patdir, auth,hosdir, cred);
        jSplitPane1.setRightComponent(profile);
    }//GEN-LAST:event_btnhospitalcataActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Fileload fileload = new Fileload();
        fileload.loadpatientfile( patdir);
        fileload.loadaddressfile(community);
        fileload.loadcredentialsfile(auth);
        fileload.loadhospitalfile(hosdir);
        fileload.loadpersonfile(perdir);
        fileload.loaddoctorfile(docdir);
        
    }//GEN-LAST:event_formWindowClosing

    private void btnpatientactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientactionActionPerformed
        // TODO add your handling code here:
        PatientActions pa=new PatientActions(community, patdir, auth, cred, hosdir, perdir,patdir.searchIndexPat(cred.getUsername()));
        jSplitPane1.setRightComponent(pa);
    }//GEN-LAST:event_btnpatientactionActionPerformed

    private void btndoccataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoccataActionPerformed
        // TODO add your handling code here:
        DoctorCatalog pa=new DoctorCatalog(community,  auth,  hosdir,cred, perdir,docdir);
        
        jSplitPane1.setRightComponent(pa);
    }//GEN-LAST:event_btndoccataActionPerformed

    private void btndocactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocactionActionPerformed
        // TODO add your handling code here:
        Doctoractions pa=new Doctoractions(community,  auth,  hosdir,cred, perdir,docdir);
        
        jSplitPane1.setRightComponent(pa);
    }//GEN-LAST:event_btndocactionActionPerformed

    private void btncommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncommunityActionPerformed
        // TODO add your handling code here:
        CreateCommunity pa=new CreateCommunity(c,cred);
        
        jSplitPane1.setRightComponent(pa);
    }//GEN-LAST:event_btncommunityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabell;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel jlusername;
    private javax.swing.JLabel jlusertype;
    // End of variables declaration//GEN-END:variables
}
