/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface.systemadminhome;

import model.confidential.Authentication;
import model.confidential.Credentials;
import model.confidential.Fileload;
import model.hospemp.Doctordirectory;
import model.hospital.CommunnityCatalog;
import model.hospital.Hospitaldirectory;
import model.patienta.Patientdirectory;
import model.persona.Community;
import model.persona.Persondirectory;
import userinterface.Homepagemjf;
import userinterface.communitya.CreateCommunity;
import userinterface.doctora.DoctorCatalog;
import userinterface.hospitala.Hospitalcatalog;
import userinterface.patient.PatientView;

/**
 *
 * @author amey8
 */
public class CommAdminhome extends javax.swing.JFrame {

    /**
     * Creates new form CommAdminhome
     */
    Credentials cred;
    Authentication auth;
    Community community;
    Patientdirectory patdir;
    Hospitaldirectory hosdir;
    Persondirectory perdir;
    Doctordirectory docdir;
    CommunnityCatalog c;
    public CommAdminhome() {
        initComponents();
        this.c=new CommunnityCatalog();
    }
    public void adminhomeinit(Community community,Patientdirectory patdir,Authentication auth,Credentials cred,
            Hospitaldirectory hosdir,Persondirectory perdir)
    {
        this.community=community;
        this.patdir=new Patientdirectory();
        this.auth=auth;
        this.cred=cred;
        this.hosdir=hosdir;
        this.perdir=perdir;
        docdir=new Doctordirectory();
        
        jlusername1.setText(cred.getUsername());
        jlusertype1.setText(cred.getUsertype());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabell1 = new javax.swing.JLabel();
        jlusername1 = new javax.swing.JLabel();
        javax.swing.JButton btnprofile1 = new javax.swing.JButton();
        javax.swing.JButton btnSignout1 = new javax.swing.JButton();
        jlusertype1 = new javax.swing.JLabel();
        javax.swing.JButton btnpatientcata1 = new javax.swing.JButton();
        javax.swing.JButton btnhospitalcata1 = new javax.swing.JButton();
        javax.swing.JButton btndoccata1 = new javax.swing.JButton();
        javax.swing.JButton btncommunity1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(950, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setOpaque(false);

        jLabell1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabell1.setText("Logged in as");
        jLabell1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlusername1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlusername1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnprofile1.setBackground(new java.awt.Color(204, 204, 204));
        btnprofile1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnprofile1.setText("View Profile");
        btnprofile1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnprofile1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnprofile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofile1ActionPerformed(evt);
            }
        });

        btnSignout1.setBackground(new java.awt.Color(204, 204, 204));
        btnSignout1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignout1.setText("Sign Out");
        btnSignout1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignout1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSignout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignout1ActionPerformed(evt);
            }
        });

        jlusertype1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlusertype1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnpatientcata1.setBackground(new java.awt.Color(204, 204, 204));
        btnpatientcata1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpatientcata1.setText("PatientCatalog");
        btnpatientcata1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnpatientcata1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpatientcata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientcata1ActionPerformed(evt);
            }
        });

        btnhospitalcata1.setBackground(new java.awt.Color(204, 204, 204));
        btnhospitalcata1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhospitalcata1.setText("HospitalCatalog");
        btnhospitalcata1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhospitalcata1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhospitalcata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhospitalcata1ActionPerformed(evt);
            }
        });

        btndoccata1.setBackground(new java.awt.Color(204, 204, 204));
        btndoccata1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndoccata1.setText("DoctorCatalog");
        btndoccata1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndoccata1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndoccata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoccata1ActionPerformed(evt);
            }
        });

        btncommunity1.setBackground(new java.awt.Color(204, 204, 204));
        btncommunity1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncommunity1.setText("Community");
        btncommunity1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncommunity1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncommunity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncommunity1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabell1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlusername1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlusertype1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncommunity1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnprofile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSignout1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnpatientcata1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnhospitalcata1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndoccata1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabell1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlusername1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlusertype1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnprofile1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpatientcata1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndoccata1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhospitalcata1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncommunity1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(btnSignout1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jSplitPane2.setLeftComponent(jPanel2);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel3);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AAROGYA MED NETWORK");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprofile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofile1ActionPerformed
        // TODO add your handling code here:
        AdminProfile profile = new AdminProfile( perdir,perdir.searchIndexPer(cred.getUsername()), community);
        jSplitPane2.setRightComponent(profile);
    }//GEN-LAST:event_btnprofile1ActionPerformed

    private void btnSignout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignout1ActionPerformed
        // TODO add your handling code here:
        Fileload fileload = new Fileload();
        fileload.loadpatientfile( patdir);
        fileload.loadaddressfile(community);
        
        fileload.loadhospitalfile(hosdir);
        fileload.loadpersonfile(perdir);
        fileload.loaddoctorfile(docdir);
        fileload.loadcommunityfile(c);
        Homepagemjf home=new Homepagemjf();
        home.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_btnSignout1ActionPerformed

    private void btnpatientcata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientcata1ActionPerformed
        // TODO add your handling code here:
        PatientView p= new PatientView(community, patdir, auth, cred, hosdir, perdir);
        jSplitPane2.setRightComponent(p);
    }//GEN-LAST:event_btnpatientcata1ActionPerformed

    private void btnhospitalcata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhospitalcata1ActionPerformed
        // TODO add your handling code here:
        Hospitalcatalog profile = new Hospitalcatalog(community,patdir, auth,hosdir, cred);
        jSplitPane2.setRightComponent(profile);
    }//GEN-LAST:event_btnhospitalcata1ActionPerformed

    private void btndoccata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoccata1ActionPerformed
        // TODO add your handling code here:
        DoctorCatalog pa=new DoctorCatalog(community,  auth,  hosdir,cred, perdir,docdir);

        jSplitPane2.setRightComponent(pa);
    }//GEN-LAST:event_btndoccata1ActionPerformed

    private void btncommunity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncommunity1ActionPerformed
        // TODO add your handling code here:
        CreateCommunity pa=new CreateCommunity(c,cred);
        
        jSplitPane2.setRightComponent(pa);
    }//GEN-LAST:event_btncommunity1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Fileload fileload = new Fileload();
        fileload.loadpatientfile( patdir);
        fileload.loadaddressfile(community);
        
        fileload.loadhospitalfile(hosdir);
        fileload.loadpersonfile(perdir);
        fileload.loaddoctorfile(docdir);
        fileload.loadcommunityfile(c);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommAdminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommAdminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommAdminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommAdminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommAdminhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabell;
    private javax.swing.JLabel jLabell1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel jlusername;
    private javax.swing.JLabel jlusername1;
    private javax.swing.JLabel jlusertype;
    private javax.swing.JLabel jlusertype1;
    // End of variables declaration//GEN-END:variables
}
