/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import dbconnection.JdbcConnect;

/**
 *
 * @author nehajoisher
 */


public class HomePageMainJF extends javax.swing.JFrame {

    /**
     * Creates new form HomePageMainJF
     */
    
    private String username;
    private String password;

    public HomePageMainJF() {
        initComponents();
        JdbcConnect connect = new JdbcConnect();
        connect.insertrec();
        
    }

    private Boolean checkBlankInput() {
        if (txtuname.getText().length() == 0 || txtpassword.getPassword().length == 0) {
            return false;
        } else {
            return true;
        }
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnNewUser = new javax.swing.JButton();
        jLabelProjName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Username");

        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });

        jLabel6.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/nehajoisher/My Folders/NEU/AED/FinalProject/parange_amey_002791448/ExpressMeds/src/userinterface/OBUZORLdEFO3HofPcHMa-1140x694.jpeg")); // NOI18N
        jLabel8.setText("jLabel8");

        btnNewUser.setText("New User");
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });

        jLabelProjName.setBackground(new java.awt.Color(219, 247, 252));
        jLabelProjName.setFont(new java.awt.Font("Telugu MN", 1, 24)); // NOI18N
        jLabelProjName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProjName.setText("ExpressMeds");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabelProjName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(51, 51, 51)
                            .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(52, 52, 52)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnLogin)
                            .addGap(28, 28, 28)
                            .addComponent(btnNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(50, 50, 50)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 79, Short.MAX_VALUE)
                    .addComponent(jLabelProjName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(160, 160, 160)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLogin)
                        .addComponent(btnNewUser))
                    .addGap(0, 155, Short.MAX_VALUE))
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (checkBlankInput()) {
         String username = txtuname.getText();
         String pass = String.valueOf(txtpassword.getPassword());
        
        }
        //        if (checkBlankInput()) {
        //            boolean checkcred = true;
        //            if (checkcred && checkbox()) {
        //                Credentials cred = new Credentials();
        //                String uname = txtuname.getText();
        //                String pass = String.valueOf(txtpassword.getPassword());
        //
        //                if (chkbxSysAdmin.isSelected()) {
        //
        //                    String role = chkbxSysAdmin.getText();
        //                    cred.setRole(role);
        //                    chkbxSysAdmin.setSelected(false);
        //                    boolean sysadmincheck = allcredentials.checkSysAdminCred(uname, pass, role);
        //                    if (sysadmincheck) {
        //                        new MainJFrame().setVisible(false);
        //                        JFrame frame = new JFrame();
        //                        frame.setPreferredSize(new Dimension(1070, 600));
        //                        SystemAdminJPanel welcomeadmin = new SystemAdminJPanel(mainSystem, allcredentials);
        //                        frame.setSize(1070, 600);
        //                        frame.setExtendedState(JFrame.MAXIMIZED_BOTH); //frame.setUndecorated(true);
        //                        frame.setVisible(true);
        //                        frame.getContentPane().add(welcomeadmin);
        //                        frame.setVisible(true);
        //                    } else {
        //                        JOptionPane.showMessageDialog(this, "Please Check your credentials");
        //                    }
        //                } else if (chkbxPatient.isSelected()) {
        //                    String role = chkbxPatient.getText();
        //                    cred.setRole(role);
        //                    chkbxPatient.setSelected(false);
        //                    boolean commadmincheck = allcredentials.checkCommAdminCred(uname, pass, role);
        //                    if (commadmincheck) {
        //                        new MainJFrame().setVisible(false);
        //                        JFrame frame = new JFrame();
        //                        frame.setPreferredSize(new Dimension(1070, 600));
        //                        PatienttJpanel welcomeadmin = new PatienttJpanel(mainSystem, allcredentials);
        //                        welcomeadmin.setVisible(true);
        //                        welcomeadmin.setSize(1070, 600);
        //                        welcomeadmin.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //
        //                    } else {
        //                        JOptionPane.showMessageDialog(this, "Please Check your credentials");
        //                    }
        //                } else if (chkbxCommAdmin.isSelected()) {
        //
        //
        //                    String role = chkbxCommAdmin.getText();
        //                    cred.setRole(role);
        //                    chkbxCommAdmin.setSelected(false);
        //                    boolean commadmincheck = allcredentials.checkCommAdminCred(uname, pass, role);
        //                    System.out.println(allcredentials.getCredential().get(0).getUsername());
        //                    if (commadmincheck) {
        //                        new MainJFrame().setVisible(false);
        //                        JFrame frame = new JFrame();
        //                        CityAdminJPanel welcomeadmin = new CityAdminJPanel(mainSystem, allcredentials);
        //                        frame.setSize(1070, 600);
        //                        frame.setExtendedState(JFrame.MAXIMIZED_BOTH); //frame.setUndecorated(true);
        //                        frame.setVisible(true);
        //                        frame.getContentPane().add(welcomeadmin);
        //                        frame.setVisible(true);
        //                    } else {
        //                        JOptionPane.showMessageDialog(this, "Please Check your credentials");
        //                    }
        //                } else if (chkbxDoctor.isSelected()) {
        //                    String role = chkbxDoctor.getText();
        //                    cred.setRole(role);
        //                    chkbxDoctor.setSelected(false);
        //                    cred.setRole(role);
        //                    chkbxDoctor.setSelected(false);
        //                    boolean commadmincheck = allcredentials.checkCommAdminCred(uname, pass, role);
        //
        //                    if (commadmincheck) {
        //                        new MainJFrame().setVisible(false);
        //                        JFrame frame = new JFrame();
        //                        DoctorAdminJPanel welcomeadmin = new DoctorAdminJPanel(mainSystem, allcredentials);
        //                        frame.setSize(900, 600);
        //                        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //                        frame.setVisible(true);
        //                        frame.getContentPane().add(welcomeadmin);
        //                        frame.setVisible(true);
        //                    } else {
        //                        JOptionPane.showMessageDialog(this, "Please check your credentials");
        //                    }
        //
        //                } else if (chkbxHospAdmin.isSelected()) {
        //                    String role = chkbxHospAdmin.getText();
        //
        //                    cred.setRole(role);
        //                    chkbxHospAdmin.setSelected(false);
        //                    cred.setRole(role);
        //                    chkbxHospAdmin.setSelected(false);
        //                    boolean commadmincheck = allcredentials.checkCommAdminCred(uname, pass, role);
        //                    if (commadmincheck) {
        //                        new MainJFrame().setVisible(false);
        //                        JFrame frame = new JFrame();
        //                        HospitalAdminJPanel welcomeadmin = new HospitalAdminJPanel(mainSystem, allcredentials);
        //                        frame.setSize(1070, 600);
        //                        frame.setExtendedState(JFrame.MAXIMIZED_BOTH); //frame.setUndecorated(true);
        //                        frame.setVisible(true);
        //                        frame.getContentPane().add(welcomeadmin);
        //                        frame.setVisible(true);
        //                    } else {
        //                        JOptionPane.showMessageDialog(this, "Please check your credentials");
        //                    }
        //                } else {
        //                    JOptionPane.showMessageDialog(this, "Please input a Role");
        //                    String role = "";
        //                }
        //                cred.setPassword(pass);
        //                cred.setUsername(uname);
        //
        //                System.out.println(pass + " " + uname + " ");
        //
        //                txtuname.setText("");
        //                txtpassword.setText("");
        //                MainJFrame mj = new MainJFrame();
        //                mj.dispose();
        //
        //
        //            } else {
        //                JOptionPane.showMessageDialog(this, "Incorrect Credentials or Role");
        //            }
        //
        //        } else {
        //
        //            JOptionPane.showMessageDialog(this, "Please Fill the fields");
        //
        //        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        // TODO add your handling code here:
        dispose();
        CustomerRegistration frame1 = new CustomerRegistration();
        frame1.setVisible(true);
        frame1.setSize(1070, 600);
        //frame1.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }//GEN-LAST:event_btnNewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageMainJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageMainJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageMainJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageMainJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageMainJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelProjName;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
