/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.hospitala;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.confidential.Authentication;
import model.confidential.Credentials;
import model.confidential.Validations;
import model.hospital.Hospital;
import model.hospital.Hospitaldirectory;
import model.patienta.Patient;
import model.patienta.Patientdirectory;
import model.persona.Address;
import model.persona.Community;

/**
 *
 * @author amey8
 */
public class Hospitalcatalog extends javax.swing.JPanel {

    /**
     * Creates new form Hospitalcatalog
     */
    Hospitaldirectory hosdir;
    Community community;
    Patientdirectory patdir;
    Credentials cred;

    public Hospitalcatalog(Community community, Patientdirectory patdir, Authentication auth, Hospitaldirectory hosdir, Credentials cred) {
        initComponents();
        this.hosdir = hosdir;
        System.out.println(hosdir.toString());
        this.community = community;
        this.patdir = patdir;
        this.cred = cred;
        populatetable();
        if (this.cred.getUsertype().equalsIgnoreCase("Community Admin"))
        {
            btnedit.setVisible(false);
        btnupdate.setVisible(false);
        btnsregister.setVisible(false);
        btndelete.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelname = new javax.swing.JLabel();
        tfhospname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfmobileno = new javax.swing.JTextField();
        tfemailid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfdesc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfhosid = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        labelname1 = new javax.swing.JLabel();
        tfstreet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfunit = new javax.swing.JTextField();
        tfcity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfstate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfzipcode = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnedit = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnsregister = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnview = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jThos = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "View Hospital", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)), "General Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Historic", 3, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        labelname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelname.setText("Name");
        labelname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfhospname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mobile No");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfmobileno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfemailid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Email id");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Description");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfdesc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Hospital id");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfhosid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tfhosid, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(tfdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(tfemailid, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(tfmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(labelname, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(tfhospname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfhosid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfhospname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfemailid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)), "Address", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Historic", 3, 14))); // NOI18N

        labelname1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelname1.setText("Street");
        labelname1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfstreet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Unit");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfunit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfcity.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("City");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("State");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfstate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Zipcode");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfzipcode.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tfzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tfstate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tfcity, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tfunit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelname1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tfstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelname1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfunit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfcity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfstate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)))
        );

        jPanel5.setOpaque(false);

        btnedit.setBackground(new java.awt.Color(204, 204, 204));
        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnedit.setText("Edit");
        btnedit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(204, 204, 204));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnupdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnsearch.setBackground(new java.awt.Color(204, 204, 204));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnsregister.setBackground(new java.awt.Color(204, 204, 204));
        btnsregister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsregister.setText("Register");
        btnsregister.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsregister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsregisterActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(204, 204, 204));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnclear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnsregister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsregister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnview.setBackground(new java.awt.Color(204, 204, 204));
        btnview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnview.setText("View");
        btnview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(204, 204, 204));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jThos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Hospital id", "Name", "Mobile No", "Email", "Street", "Unit", "City", "State", "Zipcode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jThos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        enableViewfield();
        btnedit.setEnabled(false);
        btnupdate.setEnabled(true);
        btnview.setEnabled(false);
        btnsregister.setEnabled(false);
        btnsearch.setEnabled(false);
        btndelete.setEnabled(false);


    }//GEN-LAST:event_btneditActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        btnedit.setEnabled(true);
        disableViewfield();
        //Patient updpat= new Patient();
        String thosid = tfhosid.getText();
        int taddid = hosdir.searchIndexhospital(Integer.valueOf(thosid)).getAddressid();
        String tfname = tfhospname.getText();
        String tmobileno = tfmobileno.getText();
        String temailid = tfemailid.getText();
        String tdesc = tfdesc.getText();
        String tunit = tfunit.getText();
        String tcity = tfcity.getText();
        String tstreet = tfstreet.getText();
        String tzipcode = tfzipcode.getText();
        String tstate = tfstate.getText();

        boolean er = false;

        Validations val = new Validations();
        try {

            if (tfname.isEmpty() || tmobileno.isEmpty() || temailid.isEmpty() || tdesc.isEmpty() || tunit.isEmpty()
                    || tcity.isEmpty() || tstreet.isEmpty() || tzipcode.isEmpty() || tstate.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cannot enter empty field",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                //Employee emp = new Employee();
                Hospital hos = new Hospital();
                Address add = new Address();

                hos.setHospitalid(9999);
                add.setAddress_id(9999);

                if (val.valhospname(tfname) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Name in Proper format",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    hos.setHospitalname(tfname);

                }

                if (!val.valnumber(tmobileno)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Mobile Number",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    hos.setMobileno(tmobileno);
                }
                if (val.valemailid(temailid) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Email id",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    hos.setEmail(temailid);
                    hos.setDesc(tdesc);
                }
                if (val.valstring(tcity) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter City Name in Proper format",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {

                    add.setCity(tcity);
                    add.setUnit(tunit);
                    add.setStreet(tstreet);
                }

                if (val.valstring(tstate) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Name in Proper format",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    add.setState(tstate);
                }
                if (!val.valnum(tzipcode)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Zipcode",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    add.setZipcode(tzipcode);
                    // pat.setMobileno(Integer.valueOf(tzipcode));
                }

                if (er != true) {

                    //catalog.addnewemployee(emp);
                    hos.setHospitalid(Integer.valueOf(thosid));
                    hos.setAddressid(taddid);
                    add.setAddress_id(hos.getAddressid());
                    hosdir.updatehospital(hos, hos.getHospitalid());
                    community.updateaddress(add, hos.getAddressid());


                    JOptionPane.showMessageDialog(this, "Hospital Successfully Updated!!!");

                    this.populatetable(hos);
                    btnupdate.setEnabled(false);
                    btnedit.setEnabled(true);
                    btnview.setEnabled(false);
                    btnsregister.setEnabled(false);
                    btnsearch.setEnabled(false);
                    btndelete.setEnabled(false);
                    btnclear.setEnabled(true);
                } else {

                    //catalog.deleteemprec(0);
                    hosdir.deletehospitalrec(9999);
                    community.deleteaddressrec(9999);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e + "Please Enter Valid Values",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
            hosdir.deletehospitalrec(9999);
            community.deleteaddressrec(9999);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here: 
        String query;
        Hospital hos = new Hospital();
        if (!tfhosid.getText().isEmpty()) {
            query = tfhosid.getText();
            for (Hospital emp1 : hosdir.getHosdir()) {
                if (emp1.getHospitalid() == Integer.valueOf(query)) {
                    hos = emp1;
                }
            }
        } else if (!tfhospname.getText().isEmpty()) {
            query = tfhospname.getText();
            for (Hospital emp1 : hosdir.getHosdir()) {

                if (emp1.getHospitalname().equalsIgnoreCase(query)) {
                    hos = emp1;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Search on Hospitalid or Hospital Name");
        }
        if (hos != null) {
            JOptionPane.showMessageDialog(this,
                    "Hospital Found!!!");
            populatetable(hos);
            btnsregister.setEnabled(false);
            btnupdate.setEnabled(false);
        } else
            JOptionPane.showMessageDialog(this,
                    "Hospital does not exist!!!");
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnsregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsregisterActionPerformed
        // TODO add your handling code here:
        btnedit.setEnabled(true);
        btnclear.setEnabled(true);
        btnview.setEnabled(false);
        disableViewfield();
        //Patient updpat= new Patient();

        String tfname = tfhospname.getText();
        String tmobileno = tfmobileno.getText();
        String temailid = tfemailid.getText();
        String tdesc = tfdesc.getText();
        String tunit = tfunit.getText();
        String tcity = tfcity.getText();
        String tstreet = tfstreet.getText();
        String tzipcode = tfzipcode.getText();
        String tstate = tfstate.getText();

        boolean er = false;

        Validations val = new Validations();
        try {

            if (tfname.isEmpty() || tmobileno.isEmpty() || temailid.isEmpty() || tdesc.isEmpty() || tunit.isEmpty()
                    || tcity.isEmpty() || tstreet.isEmpty() || tzipcode.isEmpty() || tstate.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cannot enter empty field",
                        "Try Again",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                //Employee emp = new Employee();
                Hospital hos = new Hospital();
                Address add = new Address();
                hos.setHospitalid(9999);
                add.setAddress_id(9999);

                if (val.valhospname(tfname) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Name in Proper format",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    hos.setHospitalname(tfname);

                }

                if (!val.valnumber(tmobileno)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Mobile Number",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    hos.setMobileno(tmobileno);
                }
                if (val.valemailid(temailid) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Email id",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    hos.setEmail(temailid);
                    hos.setDesc(tdesc);
                }
                if (val.valstring(tcity) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter City Name in Proper format",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {

                    add.setCity(tcity);
                    add.setUnit(tunit);
                    add.setStreet(tstreet);
                }

                if (val.valstring(tstate) == false) {
                    JOptionPane.showMessageDialog(this, "Please Enter Name in Proper format",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    add.setState(tstate);
                }
                if (!val.valnum(tzipcode)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Zipcode",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
                    er = true;
                } else {
                    add.setZipcode(tzipcode);
                    // pat.setMobileno(Integer.valueOf(tzipcode));
                }

                if (er != true) {
                    hos.setHospitalid();
                    add.setAddress_id();

                    hos.setAddressid(add.getAddress_id());

                    hosdir.addnewhospital(hos);
                    community.addnewaddress(add);
                    //Credentials cred = new Credentials(cred.getUsername(), cred.getUsertype(), tpassword, patient.getPersonid());
                    //auth.updatecredentials(cred, patient.getUsername(), "Patient");
                    //auth.addnewcredentials(cred);

                    JOptionPane.showMessageDialog(this, "Hospital Successfully Created!!!");
                    /*
                    tffirstname.setText("");
                    tflastname.setText("");
                    tfage.setText("");
                    tfmobileno.setText("");
                    tfstreet.setText("");
                    tfemailid.setText("");
                    tfunit.setText("");
                    tfcity.setText("");
                    listgender.clearSelection();
                    tfstate.setText("");
                    tfzipcode.setText("");
                    tfusername.setText("");
                    tfpassword.setText("");*/
                    this.populatetable(hos);
                    btnupdate.setEnabled(false);
                    btnedit.setEnabled(true);
                    btnview.setEnabled(true);
                    btnsregister.setEnabled(true);
                    btnsearch.setEnabled(true);
                    btndelete.setEnabled(true);
                } else {

                    //catalog.deleteemprec(0);
                    hosdir.deletehospitalrec(9999);
                    community.deleteaddressrec(9999);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e + "Please Enter Valid Values",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
            hosdir.deletehospitalrec(9999);
            community.deleteaddressrec(9999);
        }
    }//GEN-LAST:event_btnsregisterActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        int row = jThos.getSelectedRow();
        btnclear.setEnabled(true);
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "No row is selected! Please select one row",
                    "Select row",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) jThos.getModel();

            int selected_hosid = (int) model.getValueAt(row, 0);
            intializefields(hosdir.searchIndexhospital(selected_hosid));
            disableViewfield();
            btnsregister.setEnabled(false);
            btnsearch.setEnabled(false);
            btnupdate.setEnabled(false);
            btnedit.setEnabled(true);
        }
    }//GEN-LAST:event_btnviewActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        clearview();
        int row = jThos.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "No row is selected! Please select one row",
                    "Select row",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) jThos.getModel();

            int selected_hosid = (int) model.getValueAt(row, 0);
            hosdir.deletehospitalrec(selected_hosid);
            //addressdelete
            populatetable();
            disableViewfield();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        enableViewfield();
        tfhosid.setText("");
        tfhosid.setEnabled(true);
        tfhospname.setText("");
        tfmobileno.setText("");
        tfemailid.setText("");
        tfstreet.setText("");
        tfunit.setText("");
        tfcity.setText("");
        tfstate.setText("");
        tfzipcode.setText("");
        tfdesc.setText("");
        btnedit.setEnabled(false);
        btnupdate.setEnabled(false);
        btnview.setEnabled(true);
        btnsregister.setEnabled(true);
        btnsearch.setEnabled(true);
        btndelete.setEnabled(true);

        this.populatetableclear();
    }//GEN-LAST:event_btnclearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsregister;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnview;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jThos;
    private javax.swing.JLabel labelname;
    private javax.swing.JLabel labelname1;
    private javax.swing.JTextField tfcity;
    private javax.swing.JTextField tfdesc;
    private javax.swing.JTextField tfemailid;
    private javax.swing.JTextField tfhosid;
    private javax.swing.JTextField tfhospname;
    private javax.swing.JTextField tfmobileno;
    private javax.swing.JTextField tfstate;
    private javax.swing.JTextField tfstreet;
    private javax.swing.JTextField tfunit;
    private javax.swing.JTextField tfzipcode;
    // End of variables declaration//GEN-END:variables
    public void clearview() {
        tfhosid.setText("");
        enableViewfield();
        tfhosid.setEnabled(false);
        tfhospname.setText("");
        tfmobileno.setText("");
        tfemailid.setText("");
        tfdesc.setText("");
        tfstreet.setText("");
        tfunit.setText("");
        tfcity.setText("");
        tfstate.setText("");
        tfzipcode.setText("");
    }

    public void intializefields(Hospital hos) {
        tfhosid.setText(String.valueOf(hos.getHospitalid()));
        tfhospname.setText(hos.getHospitalname());
        tfmobileno.setText(hos.getMobileno());
        tfemailid.setText(hos.getEmail());
        tfdesc.setText(hos.getDesc());
        Address add = community.searchIndexAddress(hos.getAddressid());

        tfstreet.setText(add.getStreet());
        tfunit.setText(add.getUnit());
        tfcity.setText(add.getCity());
        tfstate.setText(add.getState());
        tfzipcode.setText(add.getZipcode());
        disableViewfield();

    }

    private void disableViewfield() {
        tfhosid.setEnabled(false);
        tfhospname.setEnabled(false);
        tfmobileno.setEnabled(false);
        tfemailid.setEnabled(false);
        tfdesc.setEnabled(false);
        tfstreet.setEnabled(false);
        tfunit.setEnabled(false);
        tfcity.setEnabled(false);
        tfstate.setEnabled(false);
        tfzipcode.setEnabled(false);

    }

    private void enableViewfield() {
        tfhospname.setEnabled(true);
        tfmobileno.setEnabled(true);
        tfemailid.setEnabled(true);
        tfdesc.setEnabled(true);
        tfstreet.setEnabled(true);
        tfunit.setEnabled(true);
        tfcity.setEnabled(true);
        tfstate.setEnabled(true);
        tfzipcode.setEnabled(true);
    }

    //Hospitaldirectory hosdir Hospital hos
    private void populatetable() {
        DefaultTableModel model = (DefaultTableModel) jThos.getModel();
        model.setRowCount(0);
        Address add;

        int i = 0;
        for (Hospital hos : hosdir.getHosdir()) {

            Object[] row = new Object[10];
            row[0] = hos.getHospitalid();
            row[1] = hos.getHospitalname();//username
            row[2] = hos.getMobileno();
            row[3] = hos.getEmail();

            add = community.searchIndexAddress(hos.getAddressid());

            row[4] = add.getStreet();
            row[5] = add.getUnit();
            row[6] = add.getCity();
            row[7] = add.getState();
            row[8] = add.getZipcode();

            model.addRow(row);

            i++;
            //JOptionPane.showMessageDialog(this, "Successfully Employee Profile Created!!!");
        }
        if (i != 0) {

            jThos.setRowSelectionInterval(0, 0);
            int row = jThos.getSelectedRow();

            int selected_hosid = (int) model.getValueAt(row, 0);

            intializefields(hosdir.searchIndexhospital(selected_hosid));

            disableViewfield();
        }

    }

    private void populatetableclear() {
        DefaultTableModel model = (DefaultTableModel) jThos.getModel();
        model.setRowCount(0);
        Address add;

        int i = 0;
        for (Hospital hos : hosdir.getHosdir()) {

            Object[] row = new Object[10];
            row[0] = hos.getHospitalid();
            row[1] = hos.getHospitalname();//username
            row[2] = hos.getMobileno();
            row[3] = hos.getEmail();
            //System.out.println(hos.getHospitalid() + "  yeda");
            add = community.searchIndexAddress(hos.getAddressid());
            //System.out.println("2");
            row[4] = add.getStreet();
            row[5] = add.getUnit();
            row[6] = add.getCity();
            row[7] = add.getState();
            row[8] = add.getZipcode();

            model.addRow(row);

            i++;
            //JOptionPane.showMessageDialog(this, "Successfully Employee Profile Created!!!");
        }

        enableViewfield();

    }

    private void populatetable(Hospital hos) {
        DefaultTableModel model = (DefaultTableModel) jThos.getModel();
        model.setRowCount(0);
        Address add;
        int i = 0;

        Object[] row = new Object[10];
        row[0] = hos.getHospitalid();
        row[1] = hos.getHospitalname();//username
        row[2] = hos.getMobileno();
        row[3] = hos.getEmail();

        add = community.searchIndexAddress(hos.getAddressid());
        row[4] = add.getStreet();
        row[5] = add.getUnit();
        row[6] = add.getCity();
        row[7] = add.getState();
        row[8] = add.getZipcode();

        model.addRow(row);

        //JOptionPane.showMessageDialog(this, "Successfully Employee Profile Created!!!");
        intializefields(hos);
        disableViewfield();
    }

}
